language: php

php:
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""
matrix:
  exclude:
  - php: 7.2
    env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
- vendor/bin/phpunit
